# Generated by Django 4.2.21 on 2025-05-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year_start', models.IntegerField()),
                ('academic_year_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_title', models.CharField(max_length=225)),
                ('highest_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=225)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.IntegerField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
                ('acad_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('course_outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_outcome', models.CharField(max_length=225)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTerm',
            fields=[
                ('course_term_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_term', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_unit', models.IntegerField()),
                ('laboratory_unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('campus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.campus')),
                ('college_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.college')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomAndSchedule',
            fields=[
                ('room_and_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_the_week', models.CharField(max_length=225)),
                ('time_starts', models.TimeField()),
                ('time_ends', models.TimeField()),
                ('building_and_room', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_and_section', models.CharField(max_length=225)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.course')),
                ('room_and_schedule_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.roomandschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.role')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=225)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.user'),
        ),
        migrations.CreateModel(
            name='RawScore',
            fields=[
                ('raw_score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.assessment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.student')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('program_outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_outcome', models.CharField(max_length=255)),
                ('course_outcome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('course_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_unit', models.CharField(max_length=225)),
                ('course_unit_percentage', models.IntegerField()),
                ('course_term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseterm')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='credit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.credit'),
        ),
        migrations.AddField(
            model_name='course',
            name='program_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.user'),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('component_name', models.CharField(max_length=225)),
                ('component_percentage', models.IntegerField()),
                ('course_unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseunit')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentClassification',
            fields=[
                ('assessment_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_classification', models.CharField(max_length=255)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='component_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.component'),
        ),
    ]
