# Generated by Django 4.2.24 on 2025-10-04 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academic_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year_start', models.IntegerField()),
                ('academic_year_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_title', models.CharField(blank=True, max_length=225, null=True)),
                ('assessment_highest_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BloomsClassification',
            fields=[
                ('blooms_classification_id', models.AutoField(primary_key=True, serialize=False)),
                ('blooms_classification_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.AutoField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=225)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_code', models.CharField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseOutcome',
            fields=[
                ('course_outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_outcome_description', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTerm',
            fields=[
                ('course_term_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_term_type', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_unit', models.IntegerField()),
                ('laboratory_unit', models.IntegerField()),
                ('credit_unit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.campus')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.college')),
            ],
        ),
        migrations.CreateModel(
            name='LoadedCourse',
            fields=[
                ('loaded_course_id', models.AutoField(primary_key=True, serialize=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ucap_backend.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.course')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_and_section', models.CharField(max_length=225)),
                ('result_sheet_remarks', models.CharField(blank=True, max_length=225, null=True)),
                ('result_sheet_status', models.CharField(blank=True, max_length=225, null=True)),
                ('instructor_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loaded_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.loadedcourse')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YearLevel',
            fields=[
                ('year_level_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_level_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('id_number', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(blank=True, max_length=225, null=True)),
                ('remarks', models.CharField(blank=True, max_length=225, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.section')),
            ],
            options={
                'unique_together': {('student_id', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ProgramOutcome',
            fields=[
                ('program_outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_outcome_description', models.CharField(max_length=255)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.program')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('course_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_unit_type', models.CharField(max_length=225)),
                ('course_unit_percentage', models.IntegerField()),
                ('course_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseterm')),
            ],
        ),
        migrations.AddField(
            model_name='courseterm',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.section'),
        ),
        migrations.CreateModel(
            name='CourseComponent',
            fields=[
                ('course_component_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_component_type', models.CharField(max_length=225)),
                ('course_component_percentage', models.IntegerField()),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseunit')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ucap_backend.credit'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ucap_backend.semester'),
        ),
        migrations.AddField(
            model_name='course',
            name='year_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ucap_backend.yearlevel'),
        ),
        migrations.CreateModel(
            name='AssessmentCourseOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.assessment')),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseoutcome')),
            ],
            options={
                'unique_together': {('assessment', 'course_outcome')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='blooms_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucap_backend.bloomsclassification'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.coursecomponent'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course_outcomes',
            field=models.ManyToManyField(through='ucap_backend.AssessmentCourseOutcome', to='ucap_backend.courseoutcome'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucap_backend.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ucap_backend.userrole'),
        ),
        migrations.CreateModel(
            name='RawScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_score', models.IntegerField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.student')),
            ],
            options={
                'unique_together': {('student', 'assessment')},
            },
        ),
        migrations.CreateModel(
            name='OutcomeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_mapping', models.CharField(blank=True, max_length=255, null=True)),
                ('course_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.courseoutcome')),
                ('program_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ucap_backend.programoutcome')),
            ],
            options={
                'unique_together': {('program_outcome', 'course_outcome')},
            },
        ),
    ]
