# Generated by Django 4.2.26 on 2025-11-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucap_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoutcome',
            name='course_outcome_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='programoutcome',
            name='program_outcome_description',
            field=models.TextField(),
        ),
    ]
