# Generated by Django 4.2.26 on 2025-11-25 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ucap_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoutcome',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_outcomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
