# Generated by Django 4.2.21 on 2025-05-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucap_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
