# Generated by Django 4.2.21 on 2025-05-14 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ucap_backend', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
