# Generated by Django 4.2.21 on 2025-05-15 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ucap_backend', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='user_id',
            new_name='instructor_assigned_id',
        ),
    ]
